### ISSUE TITLE
Crash in Node server after browser client closes RTCPeerConnection

### ISSUE THREAD

**Issue by regnaio** [murat-dogan/node-datachannel#176] opened 2023-08-14 21:17 UTC
After a successful WebRTC connection (offer created by Node server) and verifying that messages were sent and received over a `RTCDataChannel`, the browser client runs `RTCPeerConnection.close()`. This crashed the Node server with:

```shell
FATAL ERROR: Error::New napi_get_last_error_info
 1: 0xb7a940 node::Abort() [node]
 2: 0xa8e72f node::FatalError(char const*, char const*) [node]
 3: 0xa8e738 node::OOMErrorHandler(char const*, bool) [node]
 4: 0xb40ac3 napi_fatal_error [node]
 5: 0x7fbd2ce055f0 Napi::CallbackScope::~CallbackScope() [<REPO_PATH>/node_modules/node-datachannel/build/Release/node_datachannel.node]
 6: 0x7fbd2ce05918 Napi::Error::New(napi_env__*) [<REPO_PATH>/node_modules/node-datachannel/build/Release/node_datachannel.node]
 7: 0x7fbd2cdeb5d3  [<REPO_PATH>/node_modules/node-datachannel/build/Release/node_datachannel.node]
 8: 0x7fbd2ce41255 ThreadSafeCallback::callbackFunc(Napi::Env, Napi::Function, Napi::Reference<Napi::Value>*, ThreadSafeCallback::CallbackData*) [<REPO_PATH>/node_modules/node-datachannel/build/Release/node_datachannel.node]
 9: 0xb4083c  [node]
10: 0x165f601 uv_run [node]
11: 0xabda6d node::SpinEventLoop(node::Environment*) [node]
12: 0xbc1164 node::NodeMainInstance::Run() [node]
13: 0xb35bc8 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [node]
14: 0xb3976f node::Start(int, char**) [node]
15: 0x7fbd34d00d0a __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
16: 0xabbdee _start [node]
Aborted (core dumped)
```

---

### Environment:
- `node-datachannel` version: `0.4.3`
- Docker image `node:18.16.1-bullseye-slim` running on DigitalOcean droplet
- `uname -a` inside Docker container: `Linux do-sfo3-0-dev-swarm-drone-demand-node-pool-f9ed0 6.1.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1~bpo11+1 (2023-03-16) x86_64 GNU/Linux`

---

I can swap between `node-datachannel` and `wrtc` for debugging purposes. When using `wrtc`, I don't see a crash like this on the Node server after running `RTCPeerConnection.close()` on the browser client

**Comment by murat-dogan** [comment] 2023-08-21 11:02
Thanks for reporting this.
You are right `datachannel.close` and `peerconnection.destroy` are resetting callbacks.

In both cases, did you call the`.close` from browser side?
Could you please share the whole code?

**Comment by paullouisageneau** [comment] 2023-08-22 09:57
The issue here seems to be that access to the callbacks is not synchronized in the wrapper, so this code ends up assigning `PeerConnectionWrapper::mOnSignalingStateChangeCallback` at the same time as it is called in the `rtc::PeerConnection::onSignalingStateChange` callback:
```
dataChannel.onClosed(() => {
	[...]
	peerConnection.onStateChange(state => {});
	[...]
});
```

**Comment by murat-dogan** [comment] 2023-08-22 21:57
For reference;
Crashed log;
```
dataChannel.onMessage(): msg: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
2023-08-23 00:29:48.796 INFO  [23180] [rtc::impl::SctpTransport::processNotification@848] SCTP disconnected
2023-08-23 00:29:48.796 DEBUG [23274] [rtc::openssl::check@119] OpenSSL connection cleanly closed
2023-08-23 00:29:48.796 INFO  [23274] [rtc::impl::DtlsTransport::runRecvLoop@635] DTLS closed
2023-08-23 00:29:48.796 INFO  [23274] [rtc::impl::SctpTransport::incoming@454] SCTP disconnected
2023-08-23 00:29:48.796 INFO  [23181] [rtc::impl::PeerConnection::changeState@1144] Changed state to closed
2023-08-23 00:29:48.796 INFO  [23180] [rtc::impl::PeerConnection::changeState@1144] Changed state to disconnected
2023-08-23 00:29:48.796 DEBUG [23180] [rtc::impl::SctpTransport::trySendQueue@572] SCTP shutdown
2023-08-23 00:29:48.796 DEBUG [23181] [rtc::impl::SctpTransport::~SctpTransport@315] Destroying SCTP transport
2023-08-23 00:29:48.796 DEBUG [23181] [rtc::impl::DtlsTransport::stop@478] Stopping DTLS recv thread
dataChannel.onClosed()
2023-08-23 00:29:48.796 DEBUG [23181] [rtc::impl::DtlsTransport::~DtlsTransport@460] Destroying DTLS transport
2023-08-23 00:29:48.797 DEBUG [23181] [rtc::impl::IceTransport::~IceTransport@151] Destroying ICE transport
FATAL ERROR: Error::New napi_get_last_error_info
 1: 0xb09980 node::Abort() [node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [node]
 3: 0xa1c23e  [node]
 4: 0xad139b napi_fatal_error [node]
 5: 0x7ff69e2735f0 Napi::CallbackScope::~CallbackScope() [/home/murat/js/temp/test/node_modules/node-datachannel/build/Release/node_datachannel.node]
 6: 0x7ff69e273918 Napi::Error::New(napi_env__*) [/home/murat/js/temp/test/node_modules/node-datachannel/build/Release/node_datachannel.node]
 7: 0x7ff69e2595d3  [/home/murat/js/temp/test/node_modules/node-datachannel/build/Release/node_datachannel.node]
 8: 0x7ff69e2af255 ThreadSafeCallback::callbackFunc(Napi::Env, Napi::Function, Napi::Reference<Napi::Value>*, ThreadSafeCallback::CallbackData*) [/home/murat/js/temp/test/node_modules/node-datachannel/build/Release/node_datachannel.node]
 9: 0xacfddc  [node]
10: 0x1563dd1 uv_run [node]
11: 0xa43dd5 node::SpinEventLoop(node::Environment*) [node]
12: 0xb4bab6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
13: 0xacd3f2 node::Start(int, char**) [node]
14: 0x7ff6afb2d083 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
15: 0xa4076c  [node]
Aborted (core dumped)
```

NOT crashed;
```
dataChannel.onMessage(): msg: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
2023-08-23 00:36:42.745 DEBUG [23872] [rtc::openssl::check@119] OpenSSL connection cleanly closed
2023-08-23 00:36:42.745 INFO  [23776] [rtc::impl::SctpTransport::processNotification@848] SCTP disconnected
2023-08-23 00:36:42.745 INFO  [23872] [rtc::impl::DtlsTransport::runRecvLoop@635] DTLS closed
2023-08-23 00:36:42.745 INFO  [23776] [rtc::impl::PeerConnection::changeState@1144] Changed state to disconnected
2023-08-23 00:36:42.745 INFO  [23872] [rtc::impl::SctpTransport::incoming@454] SCTP disconnected
dataChannel.onClosed()
2023-08-23 00:36:42.746 DEBUG [23777] [rtc::impl::SctpTransport::trySendQueue@572] SCTP shutdown
2023-08-23 00:36:42.746 INFO  [23776] [rtc::impl::PeerConnection::changeState@1144] Changed state to closed
2023-08-23 00:36:42.746 DEBUG [23777] [rtc::impl::SctpTransport::~SctpTransport@315] Destroying SCTP transport
2023-08-23 00:36:42.746 DEBUG [23777] [rtc::impl::DtlsTransport::stop@478] Stopping DTLS recv thread
2023-08-23 00:36:42.746 DEBUG [23777] [rtc::impl::DtlsTransport::~DtlsTransport@460] Destroying DTLS transport
2023-08-23 00:36:42.746 DEBUG [23777] [rtc::impl::IceTransport::~IceTransport@151] Destroying ICE transport
```

**Comment by murat-dogan** [comment] 2023-08-23 06:42
Yes I could reproduce it with this example code. I need some time to investigate more.

Just a note, in all cases you should not need reset callbacks manually.

**Comment by paullouisageneau** [comment] 2023-08-24 14:00
I don't think the underlying issue is with the instance list. The same would happen if you changed a callback at the same time than it is called, even when not closing, because accessing and setting the `unique_ptr` (and therefore destroying the existing object) at the same time causes undefined behavior.

**Comment by paullouisageneau** [comment] 2023-08-24 15:00
Oh, I misunderstood, sorry. Thank you for working on a fix!

**Comment by murat-dogan** [comment] 2023-08-25 09:41
@paullouisageneau 
With legacy api here is the logs with notes;
```
dataChannel.onMessage(): msg: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
2023-08-25 12:36:20.984 DEBUG [73094] [DataChannelWrapper::isOpen@193] isOpen() called
2023-08-25 12:36:20.984 DEBUG [73094] [DataChannelWrapper::sendMessageBinary@163] sendMessageBinary() called
2023-08-25 12:36:20.999 DEBUG [73216] [DataChannelWrapper::onMessage@455] onMessage cb received from rtc
2023-08-25 12:36:20.999 DEBUG [73094] [DataChannelWrapper::onMessage@458] mOnMessageCallback call(1)
2023-08-25 12:36:20.999 DEBUG [73094] [DataChannelWrapper::onMessage@474] mOnMessageCallback call(2)
dataChannel.onMessage(): msg: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
// Conn Closed Here
2023-08-25 12:36:21.013 DEBUG [73321] [rtc::openssl::check@119] OpenSSL connection cleanly closed
2023-08-25 12:36:21.013 INFO  [73321] [rtc::impl::DtlsTransport::runRecvLoop@635] DTLS closed
2023-08-25 12:36:21.013 INFO  [73321] [rtc::impl::PeerConnection::changeState@1144] Changed state to disconnected
2023-08-25 12:36:21.013 INFO  [73321] [rtc::impl::SctpTransport::incoming@454] SCTP disconnected
2023-08-25 12:36:21.013 DEBUG [73321] [DataChannelWrapper::onClosed@344] onClosed cb received from rtc
2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onClosed@347] mOnClosedCallback call
// cb received from rtc and queued
2023-08-25 12:36:21.014 DEBUG [73217] [PeerConnectionWrapper::onStateChange@704] onStateChange cb received from rtc
2023-08-25 12:36:21.014 INFO  [73217] [rtc::impl::PeerConnection::changeState@1144] Changed state to closed
dataChannel.onClosed()
// cb received from rtc and queued
2023-08-25 12:36:21.014 DEBUG [73217] [PeerConnectionWrapper::onStateChange@704] onStateChange cb received from rtc
// cb changed here
2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onStateChange@683] onStateChange() called
2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onSignalingStateChange@722] onSignalingStateChange() called
2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onGatheringStateChange@762] onGatheringStateChange() called
2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onLocalDescription@603] onLocalDescription() called
2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onLocalCandidate@643] onLocalCandidate() called
2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onOpen@285] onOpen() called
2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onMessage@434] onMessage() called
2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onBufferedAmountLow@396] onBufferedAmountLow() called
2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onClosed@323] onClosed() called
2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onError@358] onError() called
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::close@275] close() called
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::doClose@256] doClose() called
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::doClose@259] Closing...

// queued cb executed here. 
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@707] mOnStateChangeCallback call(1)
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@716] mOnStateChangeCallback call(2)
// This log is from prev cb fn
peerConnection.onStateChange(): state: disconnected

// queued cb executed here. 
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@707] mOnStateChangeCallback call(1)
2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@716] mOnStateChangeCallback call(2)
// This log is from prev cb fn
peerConnection.onStateChange(): state: closed

2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::SctpTransport::~SctpTransport@315] Destroying SCTP transport
2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::DtlsTransport::stop@478] Stopping DTLS recv thread
2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::DtlsTransport::~DtlsTransport@460] Destroying DTLS transport
2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::IceTransport::~IceTransport@151] Destroying ICE transport
```

The main problem with modern api is `env` is deleted before end of cb execution. So simply adding env variable check fixes the issue.

@regnaio 
Could you please test https://github.com/murat-dogan/node-datachannel/tree/issue-176

**Comment by paullouisageneau** [comment] 2023-08-25 11:36
> @paullouisageneau With legacy api here is the logs with notes;
> 
> ```
> dataChannel.onMessage(): msg: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
> 2023-08-25 12:36:20.984 DEBUG [73094] [DataChannelWrapper::isOpen@193] isOpen() called
> 2023-08-25 12:36:20.984 DEBUG [73094] [DataChannelWrapper::sendMessageBinary@163] sendMessageBinary() called
> 2023-08-25 12:36:20.999 DEBUG [73216] [DataChannelWrapper::onMessage@455] onMessage cb received from rtc
> 2023-08-25 12:36:20.999 DEBUG [73094] [DataChannelWrapper::onMessage@458] mOnMessageCallback call(1)
> 2023-08-25 12:36:20.999 DEBUG [73094] [DataChannelWrapper::onMessage@474] mOnMessageCallback call(2)
> dataChannel.onMessage(): msg: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
> // Conn Closed Here
> 2023-08-25 12:36:21.013 DEBUG [73321] [rtc::openssl::check@119] OpenSSL connection cleanly closed
> 2023-08-25 12:36:21.013 INFO  [73321] [rtc::impl::DtlsTransport::runRecvLoop@635] DTLS closed
> 2023-08-25 12:36:21.013 INFO  [73321] [rtc::impl::PeerConnection::changeState@1144] Changed state to disconnected
> 2023-08-25 12:36:21.013 INFO  [73321] [rtc::impl::SctpTransport::incoming@454] SCTP disconnected
> 2023-08-25 12:36:21.013 DEBUG [73321] [DataChannelWrapper::onClosed@344] onClosed cb received from rtc
> 2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onClosed@347] mOnClosedCallback call
> // cb received from rtc and queued
> 2023-08-25 12:36:21.014 DEBUG [73217] [PeerConnectionWrapper::onStateChange@704] onStateChange cb received from rtc
> 2023-08-25 12:36:21.014 INFO  [73217] [rtc::impl::PeerConnection::changeState@1144] Changed state to closed
> dataChannel.onClosed()
> // cb received from rtc and queued
> 2023-08-25 12:36:21.014 DEBUG [73217] [PeerConnectionWrapper::onStateChange@704] onStateChange cb received from rtc
> // cb changed here
> 2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onStateChange@683] onStateChange() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onSignalingStateChange@722] onSignalingStateChange() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onGatheringStateChange@762] onGatheringStateChange() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onLocalDescription@603] onLocalDescription() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [PeerConnectionWrapper::onLocalCandidate@643] onLocalCandidate() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onOpen@285] onOpen() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onMessage@434] onMessage() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onBufferedAmountLow@396] onBufferedAmountLow() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onClosed@323] onClosed() called
> 2023-08-25 12:36:21.014 DEBUG [73094] [DataChannelWrapper::onError@358] onError() called
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::close@275] close() called
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::doClose@256] doClose() called
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::doClose@259] Closing...
> 
> // queued cb executed here. 
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@707] mOnStateChangeCallback call(1)
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@716] mOnStateChangeCallback call(2)
> // This log is from prev cb fn
> peerConnection.onStateChange(): state: disconnected
> 
> // queued cb executed here. 
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@707] mOnStateChangeCallback call(1)
> 2023-08-25 12:36:21.015 DEBUG [73094] [PeerConnectionWrapper::onStateChange@716] mOnStateChangeCallback call(2)
> // This log is from prev cb fn
> peerConnection.onStateChange(): state: closed
> 
> 2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::SctpTransport::~SctpTransport@315] Destroying SCTP transport
> 2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::DtlsTransport::stop@478] Stopping DTLS recv thread
> 2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::DtlsTransport::~DtlsTransport@460] Destroying DTLS transport
> 2023-08-25 12:36:21.017 DEBUG [73215] [rtc::impl::IceTransport::~IceTransport@151] Destroying ICE transport
> ```
> 
> The main problem with modern api is `env` is deleted before end of cb execution. So simply adding env variable check fixes the issue.
> 
> @regnaio Could you please test https://github.com/murat-dogan/node-datachannel/tree/issue-176

Nice fix, just a suggestion: you could do the check only once at the beginning of `ThreadSafeCallback::callbackFunc()`, which calls the argument function synchronously with the env, so you don't have to add it for every callback.

**Comment by murat-dogan** [comment] 2023-08-25 18:32
> Interesting, is the env destroyed because the callback is destroyed?

I think , yes

> Anyway, nice fix, just a suggestion: you could do the check only once at the beginning of `ThreadSafeCallback::callbackFunc()`, which calls the argument function synchronously with the env, so you don't have to add it for every callback.

I am not familiar with this code part. I guess you mean here;
https://github.com/murat-dogan/node-datachannel/blob/ffd62942419cf8c21fc5b83172bab384636f005e/src/thread-safe-callback.cpp#L48

This could be like;
```
if (!data || !env)
        return;
```

**Comment by paullouisageneau** [comment] 2023-08-25 18:39
> I am not familiar with this code part. I guess you mean here;
> 
> https://github.com/murat-dogan/node-datachannel/blob/ffd62942419cf8c21fc5b83172bab384636f005e/src/thread-safe-callback.cpp#L48
> 
> This could be like;
> 
> ```
> if (!data || !env)
>         return;
> ```

Yes, that's right.

**Closed** 2023-09-01 11:03 UTC
