### ISSUE TITLE
Degradation of connections

### ISSUE THREAD

**Issue by harbu** [murat-dogan/node-datachannel#32] opened 2021-03-02 13:13 UTC
Hello,

First of all thanks for the great library and the effort involved in putting such a thing together.

We've been using node-datachannel here at [Streamr](https://streamr.network/) for some months, and recently we stumbled upon some behavior that seems a bit weird. It seems like a bug (perhaps in the underlying native libraries), or it could be a problem in the way we use this library (or an environmental factor).

I've built a [small scale example](https://github.com/streamr-dev/node-datachannel-performance-diagnostics/tree/main/repro-buffer-issue) that reproduces the issue we have been observing in our actual project.

## Summary
It seems that after a long period of time, a WebRTC DataChannel between two clients can degrade so that bandwidth rate (in one direction) permanently drops. This doesn't seems to happen locally but rather when the clients are running on two separate machines (i.e. actual network with bandwidth and latency restrictions in-between).

### signaling-server.ts

First of all I have a simple WebSocket-based signaling server that

(a) relays WebRTC offer / answer / description messages between clients to facilitate establishing connections
(b) instructs each joining client to join to all pre-existing clients, thereby leading to a complete graph (each client has a direct connection with each other client)

https://github.com/streamr-dev/node-datachannel-performance-diagnostics/blob/main/repro-buffer-issue/signaling-server.ts

### client.ts
Implementation of a client that forms a WebSocket connection with the signaling server and WebRTC connections to other clients.

It includes the following functionality in addition to establishing WebRTC connections to other clients via the signaling server:

(a) publishes a random string of size `PACKAGE_SIZE = 800` to all connected clients (neighbors) every `INTERVAL = 2` milliseconds
(b) prints to console statistics every second: in kb/s, out kb/s, dropped messages kb/s, dataChannel bufferedAmount, state, isOpen, isPaused.
(c) Buffering of published messages: if upon trying to publish a message we notice that `dataChannel.bufferedAmount >= BUFFER_HIGH`, we set `paused = true` and start dropping messages until `paused = false`. The paused variable will be set to false when `onBufferedAmountLow` event occurs.

https://github.com/streamr-dev/node-datachannel-performance-diagnostics/blob/main/repro-buffer-issue/client.ts

### Reproducing
The code in its entirety can be found here https://github.com/streamr-dev/node-datachannel-performance-diagnostics/tree/main/repro-buffer-issue.

Basically I've set up two separate machines (one dedicated server in Germany, one dedicated server in Finland). 

Clone the project, run `npm ci` on both. 

1. Start the signaling server on one of the machines
```
npx ts-node signaling-server.ts
```

2. Start up 4 clients on the same machine as the signaling server
```
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts hel1
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts hel2
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts hel3
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts hel4
``` 

3. Start up 5 clients on the other machine
```
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts fal1
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts fal2
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts fal3
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts fal4
WS_URL=ws://signalingServerIp:8080/ npx ts-node client.ts fal5
```
4. Wait for a few seconds for all the connections to be established.

5. Now each client will be logging its statistics every second to stdout. For maybe 5-10 minutes everything looks fine. Below is an example of the logging output of a single client (`fal4` in this case) for a period of 2 seconds:

```
fal4->hel1 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel4 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel2 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel3 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal2 rate 389 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal3 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal1 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal5 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
Total 3120 / 3119 kb/s (0, 0)

fal4->hel1 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel4 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel2 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel3 rate 389 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal2 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal3 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal1 rate 391 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal5 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
Total 3123 / 3119 kb/s (0, 0)
```

Explanation:
```
fal4->fal2 rate 390 / 390 kb/s (0, 0, state=connected, open=true, paused=false)
```
- `fal4->fal2` the ids of the clients involved in this particular connection
- `390 / 390 kb/s` kilobytes in (downloaded) and out (uploaded) per second
- `(0, 0, ...)` first number is kb/s of message upload attempts that had to be dropped due to the DataChannel buffer being full, second number is current the size (in kilobytes) of the DataChannel buffer (`dataChannel.bufferedAmount()`)
- `(..., state=connected, open=true, paused=false)`, first is the value of the last call to `connection.onStateChange`, second is a boolean indicating whether the dataChannel is open or not (`this.dataChannel ? this.dataChannel.isOpen() : false`), third is indicator whether publishing messages is "paused" (i.e. we are dropping messages) due to the buffer being full

Also we are logging the sum of the first four numbers over all connections in the last line of the logging entry
```
Total 3123 / 3119 kb/s (0, 0)
```

6. After say 10-15 minutes, what will happen is that one or more of the connections arbitrarily starts buffering and then eventually dropping messages. Seemingly the upload capacity of the connection goes down slightly, and interestingly, doesn't seem to recover back to the normal capacity: 

Example of upload rate degraded (client hel2)
```
hel2->hel1 rate 354 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
hel2->hel3 rate 350 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
hel2->hel4 rate 347 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
hel2->fal1 rate 370 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
hel2->fal2 rate 377 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
hel2->fal3 rate 366 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
hel2->fal4 rate 373 / 0 kb/s (365, 5010, state=connected, open=true, paused=true)
hel2->fal5 rate 366 / 365 kb/s (0, 0, state=connected, open=true, paused=false)
Total 2903 / 2554 kb/s (365, 5010)
```

And an equivalent logging from the other side of the problematic connection (fal4)
```
fal4->hel1 rate 356 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel3 rate 351 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel2 rate 200 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->hel4 rate 345 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal1 rate 369 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal2 rate 376 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal3 rate 366 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
fal4->fal5 rate 363 / 375 kb/s (0, 0, state=connected, open=true, paused=false)
Total 2726 / 3000 kb/s (0, 0)
```

From the above logs you can see that `hel2` is at that point in time dropping all new published messages to `fal4` and just concentrating on emptying the dataChannel buffer to `fal4`.

On the other hand `fal4` is observing data coming thru (most likely what is in the buffer) but at a lower rate of 200kb/s.

Clearly all other connections are working normally, and receiving / sending data at 350-370kb/s range. Moreover, it seems like this "lowered" rate never goes back to normal but stays put. Over time more and more connections degrade in this fashion, and some of the already lowered rates can go even lower.

Both machines are equipped with a gigabyte internet connection, so the total capacity used by the clients should be under the limit. Also the clients are able to initially handle the load, which would indicate that capacity is probably not the issue here?

We are working on a version of this test based on the native C++ library, to see if we can reproduce the issue there as well.

Any help or suggestions you could provide here would be greatly appreciated!

**Comment by murat-dogan** [comment] 2021-03-02 13:44
Thank you very much for detailed explanation and test codes.

Normally I am using `node-datachannel` for transeferring data between 2 clients.
I have made tests for large data  amount (by using iperf) & long connectivity hours(about 12 hours) in the past.
But as I remember I made the tests by using `libnice` as ICE library. (`libjuice` was not providing TURN connectivity etc...)

Let me check, I will write you back.

**Comment by murat-dogan** [comment] 2021-03-04 16:56
Hi,
I have added some testing functions to the project. 
Could you please make a test as described below?

> Please use latest version (v0.0.27)

* cd into `examples` folder
* At 1. PC on 1. Shell: execute `node signaling-server.js`
* At 1. PC on 2. Shell: execute `node client-periodic.js` & note app's ID
* At 2. PC  on 1. Shell: execute `WS_URL=ws://<PC_1_IP>:8000 node client-periodic.js` & enter noted ID

Apps will start to communicate with each other & report back. 
Also `round-trip-time` and other stats will be reported.

Could you please run the test & write back if everything is stable?

You can change message size here and test for different conditions.
https://github.com/murat-dogan/node-datachannel/blob/d9836455ad2591a3072b34c4f65bb0e14fc57fcf/examples/client-server/client-periodic.js#L15

**Comment by ptesavol** [comment] 2021-03-05 12:15
Hi @murat-dogan,

I tried running your test in 2 setups: between a pair of computers connected over ipv6, rtt: 1ms, and another pair connected through IPV4 NAT("srflx","transportType":"UDP") rtt: 5ms. There were no problems in either run, SendBufferAmount stayed at 0 and the data rates stayed constant.

On the in the other hand, the buffered amount starts rising and data rate drops every time when running @harbu's example. The difference between the examples is that  @harbu's example opens multiple connections, so I suspect the problem is caused by some kind of threading issue in libdatachannel.

**Comment by murat-dogan** [comment] 2021-03-05 12:26
Actually I don't think so. 
In your tests rtt was 1ms/5ms. It means it is on a very fast connection.

The problem occurs when the connection is not so fast, we say rtt = 60ms.

In my local PC @harbu's example also running without any problem. 

The problem could be SCTP config.

**Comment by ptesavol** [comment] 2021-03-05 12:48
You are right, I introduced an artificial delay of 200ms for both uplink and downlink (rtt: 400ms) on my MAC using Network Link Conditioner, and the buffered mount started rising immediately after startup in your example: 

4# Sent: 221 KB/s / Received: 257 KB/s / SendBufferAmount: 0 / DataChannelOpen: true
5# Sent: 67 KB/s / Received: 178 KB/s / SendBufferAmount: 5500 / DataChannelOpen: true

**Comment by murat-dogan** [comment] 2021-03-05 12:57
Of course we should calculate the network latency & take into account.

https://www.switch.ch/network/tools/tcp_throughput/?mss=1280&rtt=60&loss=1e-06&Calculate=Calculate&bw=100&rtt2=80&win=64

**Comment by murat-dogan** [comment] 2021-03-07 19:59
Could you please try with 0.0.28-dev?
I published to npm also.

**Comment by harbu** [comment] 2021-03-08 14:43
Tried this one out, looks very promising! I've been running the repro experiment for 5 hours and message rates are still going 100% with no buffering. 👍

**Comment by murat-dogan** [comment] 2021-03-12 05:34
Any update on this?

**Comment by harbu** [comment] 2021-03-12 10:38
I think this issue has been resolved at least on my end. Thanks so much!

**Comment by murat-dogan** [comment] 2021-03-12 10:58
Thanks for info. So I am closing this issue.

**Closed by murat-dogan** 2021-03-12 10:58 UTC
Labels: base-lib-related, bug
